# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/krushedknight/Documents/Programming/ArduinoRoboticArm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/krushedknight/Documents/Programming/ArduinoRoboticArm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/krushedknight/Documents/Programming/ArduinoRoboticArm/CMakeFiles /Users/krushedknight/Documents/Programming/ArduinoRoboticArm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/krushedknight/Documents/Programming/ArduinoRoboticArm/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/krushedknight/Documents/Programming/ArduinoRoboticArm/CMakeFiles /Users/krushedknight/Documents/Programming/ArduinoRoboticArm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/krushedknight/Documents/Programming/ArduinoRoboticArm/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ArduinoRoboticArm

# Build rule for target.
ArduinoRoboticArm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ArduinoRoboticArm
.PHONY : ArduinoRoboticArm

# fast build rule for target.
ArduinoRoboticArm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/build
.PHONY : ArduinoRoboticArm/fast

Arm.o: Arm.cpp.o
.PHONY : Arm.o

# target to build an object file
Arm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/Arm.cpp.o
.PHONY : Arm.cpp.o

Arm.i: Arm.cpp.i
.PHONY : Arm.i

# target to preprocess a source file
Arm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/Arm.cpp.i
.PHONY : Arm.cpp.i

Arm.s: Arm.cpp.s
.PHONY : Arm.s

# target to generate assembly for a file
Arm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/Arm.cpp.s
.PHONY : Arm.cpp.s

Constants.o: Constants.cpp.o
.PHONY : Constants.o

# target to build an object file
Constants.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/Constants.cpp.o
.PHONY : Constants.cpp.o

Constants.i: Constants.cpp.i
.PHONY : Constants.i

# target to preprocess a source file
Constants.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/Constants.cpp.i
.PHONY : Constants.cpp.i

Constants.s: Constants.cpp.s
.PHONY : Constants.s

# target to generate assembly for a file
Constants.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/Constants.cpp.s
.PHONY : Constants.cpp.s

IKSolver.o: IKSolver.cpp.o
.PHONY : IKSolver.o

# target to build an object file
IKSolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/IKSolver.cpp.o
.PHONY : IKSolver.cpp.o

IKSolver.i: IKSolver.cpp.i
.PHONY : IKSolver.i

# target to preprocess a source file
IKSolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/IKSolver.cpp.i
.PHONY : IKSolver.cpp.i

IKSolver.s: IKSolver.cpp.s
.PHONY : IKSolver.s

# target to generate assembly for a file
IKSolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/IKSolver.cpp.s
.PHONY : IKSolver.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArduinoRoboticArm.dir/build.make CMakeFiles/ArduinoRoboticArm.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ArduinoRoboticArm"
	@echo "... Arm.o"
	@echo "... Arm.i"
	@echo "... Arm.s"
	@echo "... Constants.o"
	@echo "... Constants.i"
	@echo "... Constants.s"
	@echo "... IKSolver.o"
	@echo "... IKSolver.i"
	@echo "... IKSolver.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

